using System;
using System.Collections.Generic;

namespace stockAlarmSys.Models
{
    public partial class spkfk
    {
        public string spid { get; set; }
        public string spbh { get; set; }
        public string sptm { get; set; }
        public string spmch { get; set; }
        public string zjm { get; set; }
        public string beactive { get; set; }
        public string yishj { get; set; }
        public string is_gdsj { get; set; }
        public string is_gdzk { get; set; }
        public string is_tjsp { get; set; }
        public string is_hysp { get; set; }
        public string is_gmp { get; set; }
        public string is_gsp { get; set; }
        public string is_sy { get; set; }
        public string is_yp { get; set; }
        public string jingd { get; set; }
        public string denglrq { get; set; }
        public string gengxshj { get; set; }
        public string delrq { get; set; }
        public string dw { get; set; }
        public string shpchd { get; set; }
        public string shpgg { get; set; }
        public string kemuhao { get; set; }
        public string oldcode { get; set; }
        public string rkhw { get; set; }
        public string ckhw { get; set; }
        public string bzqfs { get; set; }
        public string fenlbh { get; set; }
        public string guojbh { get; set; }
        public string changjbh { get; set; }
        public string huaxm { get; set; }
        public string changym { get; set; }
        public string suming { get; set; }
        public string xiwname { get; set; }
        public string tongym { get; set; }
        public string shengccj { get; set; }
        public string pizhwh { get; set; }
        public string zhucsb { get; set; }
        public string jixing { get; set; }
        public string shiyzh { get; set; }
        public string bulfy { get; set; }
        public string chuczysx { get; set; }
        public string chuffl { get; set; }
        public string yaofpd { get; set; }
        public string yongfyyl { get; set; }
        public string jinjzh { get; set; }
        public string zhuysx { get; set; }
        public string yaowchf { get; set; }
        public string youxq { get; set; }
        public string shangplx { get; set; }
        public string guizbz { get; set; }
        public string yongyfl { get; set; }
        public string leibie { get; set; }
        public Nullable<int> jlgg { get; set; }
        public Nullable<int> otd { get; set; }
        public Nullable<int> ordercycle { get; set; }
        public Nullable<decimal> stkquot { get; set; }
        public Nullable<decimal> shlv { get; set; }
        public Nullable<decimal> hshjj { get; set; }
        public Nullable<decimal> jj { get; set; }
        public Nullable<decimal> shj { get; set; }
        public Nullable<decimal> hshsj { get; set; }
        public Nullable<decimal> lshj { get; set; }
        public Nullable<decimal> koul { get; set; }
        public Nullable<decimal> kcsx { get; set; }
        public Nullable<decimal> kcxx { get; set; }
        public Nullable<decimal> helkc { get; set; }
        public Nullable<int> bzqts { get; set; }
        public Nullable<int> yujts { get; set; }
        public Nullable<decimal> zgshl { get; set; }
        public Nullable<decimal> zhdcbj { get; set; }
        public Nullable<decimal> zdshj { get; set; }
        public Nullable<decimal> zgshj { get; set; }
        public Nullable<decimal> zgjjxz { get; set; }
        public Nullable<decimal> maolv { get; set; }
        public Nullable<decimal> huiytj { get; set; }
        public Nullable<decimal> itemlength { get; set; }
        public Nullable<decimal> itemheight { get; set; }
        public Nullable<decimal> itemwidth { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> casevolume { get; set; }
        public Nullable<decimal> caseweight { get; set; }
        public Nullable<decimal> zuixdwtj { get; set; }
        public Nullable<decimal> zuixdwzl { get; set; }
        public Nullable<decimal> pfpj { get; set; }
        public string dispcolor { get; set; }
        public Nullable<int> bzgg { get; set; }
        public string lastmodifytime { get; set; }
        public string is_cmd { get; set; }
        public string lsgg { get; set; }
        public string is_zdyh { get; set; }
        public string is_jkyp { get; set; }
        public Nullable<int> minshl { get; set; }
        public Nullable<decimal> cx_dj_kl { get; set; }
        public string is_cx_dj { get; set; }
        public string zdyh { get; set; }
        public Nullable<decimal> zdhyzklshj { get; set; }
        public string is_cyhydz { get; set; }
        public Nullable<decimal> huiyshl { get; set; }
        public string nocalcopys { get; set; }
        public string fuzr { get; set; }
        public string is_jsh { get; set; }
        public string is_lc { get; set; }
        public string is_zhongyao { get; set; }
        public string type_bh { get; set; }
        public Nullable<decimal> zdlshj { get; set; }
        public string guanjzjh { get; set; }
        public string shiyq { get; set; }
        public string abbrImageURL { get; set; }
        public string cbflbh { get; set; }
        public string imageUrl { get; set; }
        public string is_ybsp { get; set; }
        public Nullable<decimal> yb_zfbl { get; set; }
        public string yb_spbh { get; set; }
        public string username { get; set; }
        public Nullable<decimal> chuchj { get; set; }
        public Nullable<decimal> pifj { get; set; }
        public string zhilbz { get; set; }
        public string chargelb { get; set; }
        public string is_sendybzx { get; set; }
        public Nullable<decimal> tj_ylshj { get; set; }
        public string is_hj { get; set; }
        public string is_yxbz { get; set; }
        public string wdid { get; set; }
        public string chbjs { get; set; }
        public string dwbh { get; set; }
        public string zengp { get; set; }
        public string beizhu { get; set; }
        public string sp_cxxx { get; set; }
        public string spzt { get; set; }
        public string zhongbz { get; set; }
        public string cgfzr { get; set; }
        public string is_xj { get; set; }
        public Nullable<decimal> hyj { get; set; }
        public string yjj_spbh { get; set; }
        public string is_cl { get; set; }
        public Nullable<decimal> jifen { get; set; }
        public Nullable<decimal> hyj1 { get; set; }
        public Nullable<decimal> hyj2 { get; set; }
        public Nullable<decimal> hyj3 { get; set; }
        public Nullable<decimal> nhyj { get; set; }
        public Nullable<decimal> yhyj { get; set; }
        public Nullable<decimal> nhyj1 { get; set; }
        public Nullable<decimal> nhyj2 { get; set; }
        public Nullable<decimal> nhyj3 { get; set; }
        public string splx { get; set; }
        public Nullable<decimal> sp_hyjf { get; set; }
        public string is_yb { get; set; }
        public string is_jifen { get; set; }
        public string is_ggjg { get; set; }
        public string wzzt { get; set; }
        public string wzjllb { get; set; }
        public string jb1 { get; set; }
        public string jb2 { get; set; }
        public string jb3 { get; set; }
        public string jb4 { get; set; }
        public string jb5 { get; set; }
        public string jb6 { get; set; }
        public string yjfl { get; set; }
        public string ejfl { get; set; }
        public string sjfl { get; set; }
        public string chuctj { get; set; }
        public Nullable<decimal> zglshj { get; set; }
        public string spsx { get; set; }
        public string czdjbh { get; set; }
        public string sp_beizhu { get; set; }
        public string jysx { get; set; }
        public string jyzt { get; set; }
        public string qdsx { get; set; }
        public string is_bh { get; set; }
        public string dwsx { get; set; }
        public Nullable<decimal> tcdj { get; set; }
        public Nullable<decimal> tcxs { get; set; }
        public string jianz { get; set; }
        public string isybsp { get; set; }
        public Nullable<decimal> ydj { get; set; }
        public string is_hyrdz { get; set; }
        public string old_spbh { get; set; }
        public string flbh { get; set; }
        public Nullable<decimal> zdcll { get; set; }
        public Nullable<int> shzq { get; set; }
        public string splb { get; set; }
        public string dwmch { get; set; }
        public string zgys { get; set; }
        public Nullable<decimal> xshlv { get; set; }
        public string zgysbh { get; set; }
        public string yp_spbh { get; set; }
        public string spx { get; set; }
        public string danwbh { get; set; }
        public string dzjgm { get; set; }
        public string dsyyr { get; set; }
        public string dsyyr2 { get; set; }
        public string cgmd { get; set; }
        public string bhy { get; set; }
        public Nullable<decimal> dszb { get; set; }
        public Nullable<decimal> mdkcxx { get; set; }
        public string itemdiameter { get; set; }
        public string itemzq { get; set; }
        public string itemhd { get; set; }
        public string itemhsl { get; set; }
        public string is_mhj { get; set; }
        public string jwh_lastmodifytime { get; set; }
        public Nullable<decimal> bzdj { get; set; }
        public string bd_spbh { get; set; }
        public string sptm2 { get; set; }
        public string sptm3 { get; set; }
        public string yjjk_spbh { get; set; }
        public string bwm { get; set; }
        public string yjjk_shpgg { get; set; }
        public byte[] C_MASK_FROM_V2 { get; set; }
        public string thhbj { get; set; }
        public Nullable<int> istofw { get; set; }
        public Nullable<int> isfwytb { get; set; }
        public string is_dzjg { get; set; }
        public string is_ydy { get; set; }
        public string schdz { get; set; }
        public string spbctj { get; set; }
        public string yuny_tm { get; set; }
        public string yuny_jd { get; set; }
        public string cgr { get; set; }
        public string dhr { get; set; }
        public string ccfl { get; set; }
        public string yp_syff { get; set; }
        public string renq { get; set; }
        public Nullable<int> jianz2 { get; set; }
        public string yp_jixing { get; set; }
        public Nullable<decimal> dbzc { get; set; }
        public Nullable<decimal> dbzg { get; set; }
        public Nullable<decimal> dbzk { get; set; }
        public string lylx { get; set; }
        public string scqyxkz { get; set; }
        public string gsp_dist { get; set; }
        public string b2cbh { get; set; }
        public string b2ccf { get; set; }
        public string CityGSPSpec { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    }
}
